language: ruby
script: "rake spec"
branches:
  only:
    - master
matrix:
  include:
  - rvm: 2.1.8
    env: PUPPET_VERSION="~> 4.4.0"
  - rvm: 2.1.8
    env: PUPPET_VERSION="~> 4.3.0" FACTER_VERSION="~> 2.4.0"
  - rvm: 2.1.6
    env: PUPPET_VERSION="~> 4.2.0" FACTER_VERSION="~> 2.4.0"
notifications:
  email: false
gemfile: .gemfile
